# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio_producto', models.IntegerField()),
            ],
        ),
    ]
